export const MY_POSTS_REQUEST = 'MY_POSTS_REQUEST';
export const MY_POSTS_SUCCESS = 'MY_POSTS_SUCCESS';
export const MY_POSTS_FAIL = 'MY_POSTS_FAIL';
export const MY_POSTS_RESET = 'MY_POSTS_RESET';

export const POST_LIKE_REQUEST = "POST_LIKE_REQUEST"
export const POST_LIKE_SUCCESS = "POST_LIKE_SUCCESS"
export const POST_LIKE_FAIL = "POST_LIKE_FAIL"
export const POST_LIKE_RESET = "POST_LIKE_RESET"

export const POST_BOOKMARK_REQUEST = "POST_BOOKMARK_REQUEST"
export const POST_BOOKMARK_SUCCESS = "POST_BOOKMARK_SUCCESS"
export const POST_BOOKMARK_FAIL = "POST_BOOKMARK_FAIL"
export const POST_BOOKMARK_RESET = "POST_BOOKMARK_RESET"


export const LIKED_POSTS_REQUEST = "LIKED_POSTS_REQUEST"
export const LIKED_POSTS_SUCCESS = "LIKED_POSTS_SUCCESS"
export const LIKED_POSTS_FAIL = "LIKED_POSTS_FAIL"
export const LIKED_POSTS_RESET = "LIKED_POSTS_RESET"

export const BOOKMARKED_POSTS_REQUEST = "BOOKMARKED_POSTS_REQUEST"
export const BOOKMARKED_POSTS_SUCCESS = "BOOKMARKED_POSTS_SUCCESS"
export const BOOKMARKED_POSTS_FAIL = "BOOKMARKED_POSTS_FAIL"
export const BOOKMARKED_POSTS_RESET = "BOOKMARKED_POSTS_RESET"


export const MEDIA_POSTS_REQUEST = "MEDIA_POSTS_REQUEST"
export const MEDIA_POSTS_SUCCESS = "MEDIA_POSTS_SUCCESS"
export const MEDIA_POSTS_FAIL = "MEDIA_POSTS_FAIL"
export const MEDIA_POSTS_RESET = "MEDIA_POSTS_RESET"

export const TIMELINE_POSTS_REQUEST = "TIMELINE_POSTS_REQUEST"
export const TIMELINE_POSTS_SUCCESS = "TIMELINE_POSTS_SUCCESS"
export const TIMELINE_POSTS_FAIL = "TIMELINE_POSTS_FAIL"
export const TIMELINE_POSTS_RESET = "TIMELINE_POSTS_RESET"

export const POST_REQUEST = "POST_REQUEST"
export const POST_SUCCESS = "POST_SUCCESS"
export const POST_FAIL = "POST_FAIL"
export const POST_RESET = "POST_RESET"


export const POST_DETAILS_REQUEST = "POST_DETAILS_REQUEST"
export const POST_DETAILS_SUCCESS = "POST_DETAILS_SUCCESS"
export const POST_DETAILS_FAIL = "POST_DETAILS_FAIL"
export const POST_DETAILS_RESET = "POST_DETAILS_RESET"

export const CREATE_COMMENT_REQUEST = "CREATE_COMMENT_REQUEST"
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS"
export const CREATE_COMMENT_FAIL = "CREATE_COMMENT_FAIL"
export const CREATE_COMMENT_RESET = "CREATE_COMMENT_RESET"

export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST"
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS"
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL"
export const DELETE_COMMENT_RESET = "DELETE_COMMENT_RESET"

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST"
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS"
export const DELETE_POST_FAIL = "DELETE_POST_FAIL"
export const DELETE_POST_RESET = "DELETE_POST_RESET"
