export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_REGISTER_RESET = 'USER_REGISTER_RESET';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGIN_RESET = 'USER_LOGIN_RESET';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET';

export const USER_DETAILS_UPDATE_REQUEST = 'USER_DETAILS_UPDATE_REQUEST';
export const USER_DETAILS_UPDATE_SUCCESS = 'USER_DETAILS_UPDATE_SUCCESS';
export const USER_DETAILS_UPDATE_FAIL = 'USER_DETAILS_UPDATE_FAIL';
export const USER_DETAILS_UPDATE_RESET = 'USER_DETAILS_UPDATE_RESET';

export const USER_FOLLOWING_REQUEST = 'USER_FOLLOWING_REQUEST';
export const USER_FOLLOWING_SUCCESS = 'USER_FOLLOWING_SUCCESS';
export const USER_FOLLOWING_FAIL = 'USER_FOLLOWING_FAIL';
export const USER_FOLLOWING_RESET = 'USER_FOLLOWING_RESET';

export const USER_FOLLOWERS_REQUEST = 'USER_FOLLOWERS_REQUEST';
export const USER_FOLLOWERS_SUCCESS = 'USER_FOLLOWERS_SUCCESS';
export const USER_FOLLOWERS_FAIL = 'USER_FOLLOWERS_FAIL';
export const USER_FOLLOWERS_RESET = 'USER_FOLLOWERS_RESET';

export const USER_SEARCH_REQUEST = 'USER_SEARCH_REQUEST';
export const USER_SEARCH_SUCCESS = 'USER_SEARCH_SUCCESS';
export const USER_SEARCH_FAIL = 'USER_SEARCH_FAIL';
export const USER_SEARCH_RESET = 'USER_SEARCH_RESET';

export const USER_OTHER_REQUEST = 'USER_OTHER_REQUEST';
export const USER_OTHER_SUCCESS = 'USER_OTHER_SUCCESS';
export const USER_OTHER_FAIL = 'USER_OTHER_FAIL';
export const USER_OTHER_RESET = 'USER_OTHER_RESET';


export const USER_FOLLOW_REQUEST = 'USER_FOLLOW_REQUEST';
export const USER_FOLLOW_SUCCESS = 'USER_FOLLOW_SUCCESS';
export const USER_FOLLOW_FAIL = 'USER_FOLLOW_FAIL';
export const USER_FOLLOW_RESET = 'USER_FOLLOW_RESET';

export const USER_DEACTIVATE_REQUEST = 'USER_DEACTIVATE_REQUEST';
export const USER_DEACTIVATE_SUCCESS = 'USER_DEACTIVATE_SUCCESS';
export const USER_DEACTIVATE_FAIL = 'USER_DEACTIVATE_FAIL';
export const USER_DEACTIVATE_RESET = 'USER_DEACTIVATE_RESET';
